objects/SVOrderDetail__c.object
<CustomObject>
    <description>Custom order details</description>
    <fields>
        <fullName>Order_Create_Date__c</fullName>
        <label>Order Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Id__c</fullName>
        <label>Order Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Item_Id__c</fullName>
        <label>Order Item Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_SKU__c</fullName>
        <label>Product SKU</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_Quantity__c</fullName>
        <label>Sold Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>SV Order Detail</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SV Order Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ImportOrdersController.cls
public class ImportOrdersController {
   
public Blob csvFileBody{get;set;}
public string csvAsString{get;set;}
public String[] csvFileLines{get;set;}

public Boolean isUploaded {
      get { if (isUploaded == null) {  isUploaded = false; } return isUploaded; }
      set;
}

public Boolean isSaved {
      get { if (isSaved == null) {  isSaved = false; } return isSaved; }
      set;
}
    
public OrdersDAO dao;    
    
public List<SVOrderDetail__c> lOrderDetails{get;set;}
public List<String> lOrdersCreated{get;set;} 
public List<String> lOrdersFailed{get;set;} 
    
  public ImportOrdersController(){
    csvFileLines = new String[]{};
    lOrderDetails = new List<SVOrderDetail__c>();
    lOrdersCreated = new List<String>();
    lOrdersFailed =  new List<String>(); 
    dao = OrdersDAO.getDAOInstance(); // gets singleton instance  
  }
  
  public void importCSVFile() {
       try{
           reset();
           csvAsString = csvFileBody.toString();
           csvFileLines = csvAsString.split('\n'); 
           List<OrderDetailBean> lOrdDetailBeans = new List<OrderDetailBean>(); 
           for(Integer i=1;i<csvFileLines.size();i++){               
               SVOrderDetail__c orderObj = new SVOrderDetail__c();
               string[] csvRecordData = csvFileLines[i].split(',');
               
               OrderDetailBean myBean = new OrderDetailBean(
                                               csvRecordData[1],
                                               csvRecordData[0],
                                               csvRecordData[4],
                                               Integer.valueOf(csvRecordData[2]),
                                               Double.valueOf(csvRecordData[3]),
                                               DateTime.valueOf(csvRecordData[5])
                                              );
               lOrdDetailBeans.add(myBean);
           }
        //insert lOrderDetails;
        lOrderDetails.clear();
        lOrderDetails.addAll(dao.storeCSVOrderDetails(lOrdDetailBeans));   
        
        isUploaded = true;   
        }
        catch (Exception e)
        {
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while importing data. Please make sure input csv file is valid!');
            ApexPages.addMessage(errorMessage);
        }  
  }
    
  public void createOrders() {
       System.debug('SV: In createOrders()'); 
       Set<String> sInputSKUs = new Set<String>();
       // Creating map of <orderId,List of OrderItemDetailBeans>
       Map<String, List<OrderDetailBean>>  mOrders = new Map<String, List<OrderDetailBean>>();
        for (SVOrderDetail__c dtl : lOrderDetails) {
            sInputSKUs.add(dtl.product_sku__c);
            OrderDetailBean myBean = new OrderDetailBean(
                                               dtl.order_item_id__c,
                                               dtl.Order_Id__c,
                                               dtl.product_sku__c,
                                               Integer.valueOf(dtl.sold_quantity__c),
                                               Double.valueOf(dtl.Unit_Price__c),
                                               dtl.Order_Create_Date__c
                                              );
            // if map has orderId with empty list of beans
            if (mOrders.get(dtl.order_id__c) == null) {
               List<OrderDetailBean> newList = new List<OrderDetailBean>();
               newList.add(myBean); 
               mOrders.put(dtl.order_id__c, newList) ;
            } else {
               List<OrderDetailBean> existingList = mOrders.get(dtl.order_id__c);
               existingList.add(myBean);
               mOrders.put(dtl.order_id__c, existingList) ; 
            }
        }
        reset(); 
        Set<String> ordersCreated = dao.storeOrders(mOrders, sInputSKUs);
        //lOrdersCreated.clear();
        lOrdersCreated.addAll(ordersCreated);
        
        Set<String> ordersFailed  = new Set<String>();
        for (String key : mOrders.keySet()) {
            if (!ordersCreated.contains(key)) {
               ordersFailed.add(key); 
            }  
        }
        //lOrdersFailed.clear();
        lOrdersFailed.addAll(ordersFailed);
        isSaved = true;
    }
    
    public void reset() {
       //csvFileBody=null; 
       lOrderDetails.clear();
       lOrdersCreated.clear();
       lOrdersFailed.clear();
    }
}